name: Update Readme

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  update_readme:
    name: Update Readme
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Generate Readme
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: ./generate_readme.sh
      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.DYNAMO_ACTIONS_TOKEN }}
        shell: bash
        run: |
          git config --local user.email "dynamo@autodesk.com"
          git config --local user.name "dynamo-ci-user"
          git add .
          git commit -m "Update Readme"
          git push
