name: Update Readme

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  update_readme:
    name: Update Readme
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Generate Readme
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: ./generate_readme.sh
      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.DYNAMO_ACTIONS_TOKEN }}
        shell: bash
        run: |
          git config --local user.email "dynamo@autodesk.com"
          git config --local user.name "dynamo-ci-user"
          git add .
          git commit -m "Update Readme"
          git push
